name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build current project using platformio 
        uses: docker://sglahn/platformio-core:latest
        with:
          args: run